server:
  port: 9008
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/wipro 
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: 'create-drop'
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

  config:
    import: optional:configserver:http://localhost:9092
    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true